import image1 from './images/casual/casual1.jpg'
import image2 from './images/formal/formal1.jpg'
import image3 from './images/casual/casual2.jpg';
import image4 from './images/formal/formal2.jpg';
import image5 from './images/casual/casual3.jpg';
import image6 from './images/formal/formal3.jpg';
import image7 from './images/casual/casual4.jpg';
import image8 from './images/formal/formal4.jpg';
import image9 from './images/casual/casual5.jpg';
import image10 from './images/formal/formal5.jpg';

const productsData = [
  {
    id: 1,
    name: 'Dress 1',
    image: `${image1}`,
    category: 'Casual',
    color: 'Grey',
    size: 'Medium',
    price: 49.99,
    popularity: 5, 
    isNewArrival: false,
  },
  {
    id: 2,
    name: 'Dress 2',
    image: `${image2}`,
    category: 'Formal',
    color: 'Red',
    size: 'Large',
    price: 79.99,
    popularity: 4,
    isNewArrival: true,
  },
  {
    id: 3,
    name: 'Dress 3',
    image: `${image3}`,
    category: 'Casual',
    color: 'Black',
    size: 'Small',
    price: 39.99,
    popularity: 3,
    isNewArrival: true,
  },
  {
    id: 4,
    name: 'Dress 4',
    image: `${image4}`,
    category: 'Formal',
    color: 'Blue',
    size: 'Medium',
    price: 89.99,
    popularity: 5,
    isNewArrival: false,
  },
  {
    id: 5,
    name: 'Dress 5',
    image: `${image5}`,
    category: 'Casual',
    color: 'Black',
    size: 'Large',
    price: 59.99,
    popularity: 4,
    isNewArrival: false,
  },
  {
    id: 6,
    name: 'Dress 6',
    image: `${image6}`,
    category: 'Formal',
    color: 'Black',
    size: 'Small',
    price: 69.99,
    popularity: 3,
    isNewArrival: true,
  },
  {
    id: 7,
    name: 'Dress 7',
    image: `${image7}`,
    category: 'Casual',
    color: 'White',
    size: 'Medium',
    price: 44.99,
    popularity: 5,
    isNewArrival: true,
  },
  {
    id: 8,
    name: 'Dress 8',
    image: `${image8}`,
    category: 'Formal',
    color: 'Blue',
    size: 'Large',
    price: 74.99,
    popularity: 4,
    isNewArrival: false,
  },
  {
    id: 9,
    name: 'Dress 9',
    image: `${image9}`,
    category: 'Casual',
    color: 'Blue',
    size: 'Small',
    price: 54.99,
    popularity: 3,
    isNewArrival: false,
  },
  {
    id: 10,
    name: 'Dress 10',
    image: `${image10}`,
    category: 'Formal',
    color: 'Blue',
    size: 'Medium',
    price: 99.99,
    popularity: 5,
    isNewArrival: true,
  },
  {
    id: 11,
    name: 'Dress 11',
    image: ``,
    category: 'Casual',
    color: 'Orange',
    size: 'Large',
    price: 64.99,
    popularity: 4,
    isNewArrival: true,
  },
  {
    id: 12,
    name: 'Dress 12',
    image: ``,
    category: 'Formal',
    color: 'Turquoise',
    size: 'Small',
    price: 79.99,
    popularity: 3,
    isNewArrival: false,
  },
  {
    id: 13,
    name: 'Dress 13',
    image: ``,
    category: 'Casual',
    color: 'Lilac',
    size: 'Medium',
    price: 49.99,
    popularity: 4,
    isNewArrival: true,
  },
  {
    id: 14,
    name: 'Dress 14',
    image: ``,
    category: 'Formal',
    color: 'Silver',
    size: 'Large',
    price: 89.99,
    popularity: 5,
    isNewArrival: false,
  },
  {
    id: 15,
    name: 'Dress 15',
    image: ``,
    category: 'Casual',
    color: 'Mint',
    size: 'Small',
    price: 39.99,
    popularity: 3,
    isNewArrival: false,
  },
  {
    id: 16,
    name: 'Dress 16',
    image: ``,
    category: 'Formal',
    color: 'Gold',
    size: 'Medium',
    price: 69.99,
    popularity: 4,
    isNewArrival: true,
  },
  {
    id: 17,
    name: 'Dress 17',
    image: ``,
    category: 'Casual',
    color: 'Coral',
    size: 'Large',
    price: 54.99,
    popularity: 5,
    isNewArrival: true,
  },
  {
    id: 18,
    name: 'Dress 18',
    image: ``,
    category: 'Formal',
    color: 'Charcoal',
    size: 'Small',
    price: 79.99,
    popularity: 3,
    isNewArrival: false,
  },
  {
    id: 19,
    name: 'Dress 19',
    image: ``,
    category: 'Casual',
    color: 'Peach',
    size: 'Medium',
    price: 59.99,
    popularity: 4,
    isNewArrival: false,
  },
  {
    id: 20,
    name: 'Dress 20',
    image: ``,
    category: 'Formal',
    color: 'Plum',
    size: 'Large',
    price: 74.99,
    popularity: 5,
    isNewArrival: true,
  },
  {
    id: 21,
    name: 'Dress 21',
    image: ``,
    category: 'Casual',
    color: 'Slate',
    size: 'Small',
    price: 44.99,
    popularity: 3,
    isNewArrival: true,
  },
  {
    id: 22,
    name: 'Dress 22',
    image: ``,
    category: 'Formal',
    color: 'Rose',
    size: 'Medium',
    price: 64.99,
    popularity: 4,
    isNewArrival: false,
  },
  {
    id: 23,
    name: 'Dress 23',
    image: ``,
    category: 'Casual',
    color: 'Sky Blue',
    size: 'Large',
    price: 55.99,
    popularity: 4,
    isNewArrival: true,
  },
  {
    id: 24,
    name: 'Dress 24',
    image: ``,
    category: 'Formal',
    color: 'Burgundy',
    size: 'Medium',
    price: 79.99,
    popularity: 5,
    isNewArrival: false,
  },
  // Add more dresses...
];

export default productsData;
